<template>
  <section class="mcp-panel">
    <div class="mcp-hero"><div><span class="mcp-eyebrow">集成与发布 / OpenClaw 兼容客户端</span><h2>云枢 MCP 服务</h2><p>CPClaw 统一管理云枢环境与元数据；任意 OpenClaw 兼容客户端可携带使用者自己的云枢账号和密码调用已发布的 MCP 工具。</p></div><el-tag :type="statusType" effect="plain" round>{{ statusLabel }}</el-tag></div>
    <el-alert class="mcp-boundary" type="info" show-icon :closable="false"><template #title>配置边界</template>云枢访问地址来自 CPClaw 已配置的云枢环境，不需要在此重复填写。终端账号和密码必须在 MCP 客户端配置中填写，不会保存到 CPClaw 数据库。</el-alert>

    <el-card class="mcp-card" shadow="never"><template #header><div class="mcp-card-title"><strong>服务发布</strong><small>发布后，OpenClaw 兼容客户端可直接通过 SSE 连接 CPClaw；无需安装脚本或提供 CPClaw 安装目录。</small></div></template><el-form label-position="top" class="mcp-form"><el-form-item label="MCP 安装标识"><el-input v-model="form.installationId" readonly><template #append><el-button @click="copyInstallationId">复制</el-button></template></el-input></el-form-item><el-form-item label="终端名称"><el-input v-model="form.displayName" readonly /></el-form-item><el-form-item label="云枢环境"><div class="environment-state"><span :class="['environment-dot',{ready:installation?.environmentConfigured}]" /><span>{{ installation?.environmentConfigured ? '已使用 CPClaw 配置的云枢环境' : 'CPClaw 尚未配置云枢环境地址' }}</span></div></el-form-item><el-form-item label="MCP 客户端配置片段"><el-input :model-value="configText" type="textarea" :rows="8" readonly /></el-form-item><div class="mcp-actions"><el-button type="primary" :loading="publishing" :disabled="!installation?.environmentConfigured" @click="publish"><el-icon><CircleCheck /></el-icon>{{ isEnabled ? '更新发布配置' : '发布 MCP 服务' }}</el-button><el-button v-if="isEnabled" text type="danger" :loading="disabling" @click="disable">停用 MCP</el-button></div><el-alert v-if="message" :type="messageType" show-icon :closable="false" :title="message" /></el-form></el-card>

    <el-card class="mcp-card" shadow="never"><template #header><div class="mcp-card-title"><strong>终端接入说明</strong><small>当前联调阶段使用云枢账号密码；后续可在不改变 SSE 地址和工具协议的前提下切换为 API Key。</small></div></template><ol class="mcp-guide"><li><span>1</span><div><strong>管理员发布服务</strong><small>确认 CPClaw 已配置云枢环境，然后复制 SSE 配置片段。</small></div></li><li><span>2</span><div><strong>终端配置 MCP 客户端</strong><small>当前在 <code>headers</code> 中设置 <code>x-cpclaw-cloudpivot-username</code> 和 <code>x-cpclaw-cloudpivot-password</code>；后续切换 API Key 时只替换凭据字段。</small></div></li><li><span>3</span><div><strong>调用 MCP 工具</strong><small>客户端通过 HTTPS 直接调用 CPClaw；CPClaw 不持久化终端凭据，并保留脱敏调用审计。</small></div></li></ol></el-card>

    <el-card class="mcp-card" shadow="never"><template #header><div class="mcp-card-title"><strong>能力清单</strong><small>未验证的写操作不会被 MCP 自动执行。</small></div></template><div class="mcp-capabilities"><div v-for="capability in installation?.capabilities ?? []" :key="capability.name" class="mcp-capability"><span class="mcp-capability-dot" :class="`is-${capability.status}`" /><div><strong>{{ capability.name }}</strong><small>{{ capability.rule }}</small></div><el-tag size="small" effect="plain">{{ capabilityLabel(capability.status) }}</el-tag></div></div></el-card>
  </section>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { CircleCheck } from '@element-plus/icons-vue'
import { disableCloudPivotMcp, enableCloudPivotMcp, getCloudPivotMcp } from '../../services/mcpApi'
import type { McpCloudPivotBindingRequest, McpCloudPivotInstallation } from '../../types/mcp'

const installation = ref<McpCloudPivotInstallation>(); const publishing = ref(false); const disabling = ref(false); const message = ref(''); const messageType = ref<'success' | 'warning' | 'info' | 'error'>('info')
const form = reactive<McpCloudPivotBindingRequest>({ installationId: '', displayName: '' })
const isEnabled = computed(() => installation.value?.status === 'ENABLED'); const statusLabel = computed(() => installation.value?.status === 'ENABLED' ? '已发布' : installation.value?.status === 'DISABLED' ? '已停用' : '待发布'); const statusType = computed(() => installation.value?.status === 'ENABLED' ? 'success' : installation.value?.status === 'DISABLED' ? 'info' : 'warning'); const configText = computed(() => JSON.stringify({ CloudPivotMCP: installation.value?.mcpClientConfig ?? {} }, null, 2))
onMounted(() => { void load() })
async function load() { try { installation.value = await getCloudPivotMcp(); Object.assign(form, { installationId: installation.value.installationId, displayName: installation.value.displayName }) } catch (error) { setMessage(error, '加载 MCP 状态失败', 'error') } }
async function publish() { publishing.value = true; try { installation.value = await enableCloudPivotMcp({ ...form }); setMessage('MCP 服务已发布。请将配置片段提供给 OpenClaw 兼容客户端的终端用户。', 'success') } catch (error) { setMessage(error, '发布 MCP 服务失败', 'error') } finally { publishing.value = false } }
async function disable() { disabling.value = true; try { installation.value = await disableCloudPivotMcp(form.installationId); setMessage('MCP 服务已停用。', 'info') } catch (error) { setMessage(error, '停用 MCP 失败', 'error') } finally { disabling.value = false } }
async function copyInstallationId() { await navigator.clipboard?.writeText(form.installationId); ElMessage.success('安装标识已复制') }
function setMessage(error: unknown, fallback: string, type: 'success' | 'warning' | 'info' | 'error') { messageType.value = type; message.value = error instanceof Error && error.message ? error.message : fallback }
function capabilityLabel(status: string) { return status === 'enabled' ? '可用' : status === 'verified-readonly' ? '只读已验证' : status === 'confirmation-required' ? '需确认' : status }
</script>

<style scoped>
.mcp-panel{display:grid;max-width:980px;gap:16px}.mcp-hero{display:flex;align-items:flex-start;justify-content:space-between;gap:24px}.mcp-eyebrow{color:var(--settings-brand);font-size:11px;font-weight:600;letter-spacing:.08em}.mcp-hero h2{margin:8px 0 7px;font-size:clamp(25px,3vw,34px);font-weight:650;letter-spacing:-.025em}.mcp-hero p{max-width:760px;margin:0;color:var(--settings-secondary);font-size:13.5px;line-height:1.65}.mcp-boundary{align-items:flex-start;border-radius:10px}.mcp-card{border-color:var(--settings-line);border-radius:var(--settings-radius);background:var(--settings-surface);box-shadow:none}.mcp-card :deep(.el-card__header){padding:18px 22px;border-color:var(--settings-line)}.mcp-card :deep(.el-card__body){padding:22px}.mcp-card-title{display:grid;gap:4px}.mcp-card-title small,.mcp-guide small{color:var(--settings-secondary);font-size:12px;line-height:1.5}.mcp-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 16px}.mcp-form .el-form-item:nth-child(3),.mcp-form .el-form-item:nth-child(4),.mcp-actions,.mcp-form .el-alert{grid-column:1/-1}.mcp-form :deep(.el-textarea__inner){font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:12px;line-height:1.5}.environment-state{display:flex;min-height:42px;align-items:center;gap:9px;padding:0 12px;border:1px solid var(--settings-line);border-radius:8px;color:var(--settings-secondary);font-size:13px}.environment-dot,.mcp-capability-dot{width:8px;height:8px;border-radius:50%;background:#f59e0b}.environment-dot.ready,.mcp-capability-dot.is-enabled{background:#22c55e}.mcp-capability-dot.is-verified-readonly{background:#4f6ef7}.mcp-actions{display:flex;flex-wrap:wrap;gap:10px;padding-top:18px;border-top:1px solid var(--settings-line)}.mcp-guide{display:grid;gap:2px;margin:0;padding:0;list-style:none}.mcp-guide li{display:grid;grid-template-columns:24px minmax(0,1fr);gap:10px;padding:11px 0;border-bottom:1px solid var(--settings-line)}.mcp-guide li:last-child{border-bottom:0}.mcp-guide li>span{color:var(--settings-tertiary);font-size:11px;font-weight:600}.mcp-guide div,.mcp-capability div{display:grid;gap:3px}.mcp-guide strong,.mcp-capability strong{font-size:13px}.mcp-guide code{padding:1px 4px;border-radius:4px;background:var(--settings-surface-soft);font-size:11px}.mcp-capabilities{display:grid;gap:2px}.mcp-capability{display:grid;grid-template-columns:10px minmax(0,1fr) auto;align-items:center;gap:12px;padding:12px 0;border-bottom:1px solid var(--settings-line)}.mcp-capability:last-child{border-bottom:0}.mcp-capability small{color:var(--settings-secondary);font-size:12px;line-height:1.45}@media(max-width:620px){.mcp-hero{flex-direction:column;gap:12px}.mcp-form{grid-template-columns:1fr}.mcp-form .el-form-item:nth-child(3),.mcp-form .el-form-item:nth-child(4),.mcp-actions,.mcp-form .el-alert{grid-column:auto}.mcp-actions{align-items:stretch;flex-direction:column}.mcp-actions .el-button{width:100%;margin-left:0}}
</style>
